package br.com.castelobranco.concessionaria.modelo;
// Generated May 6, 2015 3:18:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private long codigo;
     private String marca;
     private String modelo;
     private String cor;
     private int ano;
     private double preco;
     private Set vendas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(long codigo, String marca, String modelo, String cor, int ano, double preco) {
        this.codigo = codigo;
        this.marca = marca;
        this.modelo = modelo;
        this.cor = cor;
        this.ano = ano;
        this.preco = preco;
    }
    public Produto(long codigo, String marca, String modelo, String cor, int ano, double preco, Set vendas) {
       this.codigo = codigo;
       this.marca = marca;
       this.modelo = modelo;
       this.cor = cor;
       this.ano = ano;
       this.preco = preco;
       this.vendas = vendas;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


