package br.com.castelobranco.concessionaria.modelo;
// Generated May 6, 2015 3:18:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private long codigo;
     private Produto produto;
     private Date data;
     private long registroVendedor;
     private double desconto;
     private double valorAcessorio;
     private double valorTotal;

    public Venda() {
    }

    public Venda(long codigo, Produto produto, Date data, long registroVendedor, double desconto, double valorAcessorio, double valorTotal) {
       this.codigo = codigo;
       this.produto = produto;
       this.data = data;
       this.registroVendedor = registroVendedor;
       this.desconto = desconto;
       this.valorAcessorio = valorAcessorio;
       this.valorTotal = valorTotal;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public long getRegistroVendedor() {
        return this.registroVendedor;
    }
    
    public void setRegistroVendedor(long registroVendedor) {
        this.registroVendedor = registroVendedor;
    }
    public double getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(double desconto) {
        this.desconto = desconto;
    }
    public double getValorAcessorio() {
        return this.valorAcessorio;
    }
    
    public void setValorAcessorio(double valorAcessorio) {
        this.valorAcessorio = valorAcessorio;
    }
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }




}


